import { Inter } from '@next/font/google'
import Head from 'next/head'
import Header from '../components/molecules/Header'
import Post from '../components/organisms/Post'
import styles from '../styles/Home.module.scss'
import { Post as PostType } from '../types/organisms/Post'
import { PostCard } from '../components/organisms/PostCard'
import { PostCard as PostCardType } from '../types/organisms/PostCard'
import { PostHead } from '../types/molecules/PostHead'
import { Title } from '../types/atoms/Title'
import { Tag } from '../types/atoms/Tag'
import { Created } from '../types/atoms/Created'
import { Body } from '../types/atoms/Body'
import { InternalPath } from '../types/atoms/InternalPath'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const body = new Body(`
  # h1

  ## h2

  ### h3

  * list
    * hoge
    * fuga
    * piyo

  * strong

  **hogeeeee**

  * strikethrough

  ~~fugafuga~~

  * italic

  _piyopiyo_

  [https://numnam.net](https://numnam.net)

  ~~~js
  const hoge = 'hoge'

  console.log(hoge)
  ~~~
  `)

  const tags = [
    new Tag('fugafuga'),
  ]

  const title = new Title('hogehoge')

  const created = new Created('2023-02-23 00:00:00')

  const internalPath = new InternalPath('/hoge')

  const postHead = new PostHead(
    title,
    tags,
    created
  )

  const post = new PostType(
    postHead,
    body
  )

  const postCard = new PostCardType(
    postHead,
    internalPath
  )

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header />
        <Post post={post} />
        <PostCard post={postCard} />
      </main>
    </>
  )
}
