import { Inter } from '@next/font/google'
import Head from 'next/head'
import Header from '../components/molecules/Header'
import Post from '../components/organisms/Post'
import styles from '../styles/Home.module.scss'
import { Post as PostType } from '../types/organisms/Post'

const inter = Inter({ subsets: ['latin'] })

export default function Home() {
  const body = `
  # h1

  ## h2

  ### h3

  * list
    * hoge
    * fuga
    * piyo
  
  * strong

  **hogeeeee**

  * strikethrough

  ~~fugafuga~~

  * italic

  _piyopiyo_

  [https://numnam.net](https://numnam.net)

  ~~~js
  const hoge = 'hoge'

  console.log(hoge)
  ~~~
  `

  const tags = [
    'fugafuga',
  ]

  const title = 'hogehoge'

  const created = '2023-02-23 00:00:00'

  const post = new PostType(
    title,
    tags,
    body,
    created
  )

  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className={styles.main}>
        <Header />
        <Post post={post} />
      </main>
    </>
  )
}
